# Configuration for Dart analyzer

analyzer:
  # Exclude specific directories or files from analysis
  exclude:
    - "**/*.g.dart"  # Exclude generated files
    - "build/**"      # Exclude build directory
    - "android/**"    # Exclude Android directory
    - "ios/**"        # Exclude iOS directory

# Configuration for Dart linter (static analysis tool)
linter:
  # Define lint rules and configurations
  rules:
    # Prefer using const constructors where possible
    prefer_const_constructors: true
    # Prefer using const literals to create immutables
    prefer_const_literals_to_create_immutables: true
    # Prefer using const constructors in immutables
    prefer_const_constructors_in_immutables: true
    # Prefer declaring final fields
    prefer_final_fields: true
    # Prefer declaring final variables in local scope
    prefer_final_locals: true
    # Prefer using if-null operator (??) over nullable expressions
    prefer_if_null_operators: true
    # Prefer using void as return type when no value is returned
    prefer_void_to_null: true
    # Avoid classes with only static members
    avoid_classes_with_only_static_members: true
    # Sort constructors first in a class definition
    sort_constructors_first: true
    # Sort unnamed constructors first in a class definition
    sort_unnamed_constructors_first: true
    # Prefer asserts in initializer lists
    prefer_asserts_in_initializer_lists: true
    # Prefer for elements over map fromIterable
    prefer_for_elements_to_map_fromIterable: true
    # Prefer using forEach over for-in loops
    prefer_foreach: true
    # Prefer inlined additions for numerical types
    prefer_inlined_adds: true
    # Prefer using single quotes for string literals
    prefer_single_quotes: true
    # Use function type syntax for parameters
    use_function_type_syntax_for_parameters: true
    # Use 'key' parameter in widget constructors
    use_key_in_widget_constructors: true
    # Avoid using print statements
    avoid_print: true

# Include additional lint rules from the flutter_lints package
include: package:flutter_lints/flutter.yaml
