name: dwaweenx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  intl: any
  audio_video_progress_bar: ^2.0.1
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.14
  bottom_navy_bar: ^6.0.0
  fluttertoast:
  share_plus: ^7.1.0
  flutter_spinkit: ^5.1.0
  screenshot: ^2.1.0
  provider: ^6.1.1
  easy_localization: ^3.0.3
  collection: ^1.17.2
  firebase_storage: ^11.6.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  # sqflite: ^2.3.0
  # path: ^1.8.3
  # path_provider: ^2.1.2
  # dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter pub get
  #dart run launcher_name:main
  launcher_name: ^1.0.2

  #flutter pub get
  #flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

launcher_name:
  default: "Dawaween"
  ar: "دواوين"
  fr: "recueils"
  en: "Dawaween"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher/launcher.png"
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/paintings/
    - assets/images/icons/
    - assets/img/
    - assets/ico/
    - assets/json/
    - assets/img/download.png
    - assets/lang/

  fonts:
    - family: Amiri Regular
      fonts:
        - asset: assets/fonts/AmiriRegular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700